# Generated by Django 3.0.4 on 2020-06-12 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(default='No title', max_length=100)),
                ('shortDescription', models.TextField(default='No short description', max_length=300)),
                ('longDescription', models.TextField(default='No short description', max_length=300)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('link', models.CharField(default='No link given', max_length=100)),
                ('pic1', models.CharField(default='No image', max_length=100)),
                ('pic1Description', models.CharField(default='Description of picture', max_length=100)),
                ('pic2', models.CharField(default='No image', max_length=100)),
                ('pic2Description', models.CharField(default='Description of picture', max_length=100)),
                ('pic3', models.CharField(default='No image', max_length=100)),
                ('pic3Description', models.CharField(default='Description of picture', max_length=100)),
            ],
        ),
    ]
