# Generated by Django 3.0.4 on 2020-03-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=3000)),
                ('topPicphoto', models.ImageField(upload_to='cars')),
                ('middlePicphoto', models.ImageField(upload_to='cars')),
                ('middlePicDescription', models.CharField(max_length=300)),
            ],
        ),
    ]
