# Generated by Django 3.0.4 on 2020-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200502_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='middlePicphoto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='topPicphoto',
            field=models.CharField(max_length=100),
        ),
    ]
