# Generated by Django 3.0.4 on 2020-05-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200504_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='middlePicDescription',
        ),
        migrations.AddField(
            model_name='post',
            name='middlePicphotoDescription',
            field=models.CharField(default='Description of middle picture', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='topPicphotoDescription',
            field=models.CharField(default='Description of top picture', max_length=100),
        ),
    ]
