# Generated by Django 3.0.4 on 2020-05-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200514_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='middlePicphoto',
            new_name='middleImage',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='middlePicphotoDescription',
            new_name='middleImageDescription',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topPicphoto',
            new_name='topImage',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topPicphotoDescription',
            new_name='topImageDescription',
        ),
    ]
