# Generated by Django 3.0.4 on 2020-05-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200514_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='github',
            new_name='repo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='youtube',
            new_name='video',
        ),
    ]
