# Generated by Django 3.0.4 on 2020-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200514_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='references',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
