# Generated by Django 3.0.4 on 2020-05-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='references',
        ),
        migrations.AddField(
            model_name='post',
            name='reference1Link',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='reference1Text',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
