# Generated by Django 3.0.4 on 2020-05-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200514_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reference2Link',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='reference2Text',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
