# Generated by Django 3.0.4 on 2020-05-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200514_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reference1Link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference1Text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference2Link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference2Text',
        ),
        migrations.AddField(
            model_name='post',
            name='references',
            field=models.TextField(default='none', max_length=1000),
        ),
    ]
