# Generated by Django 3.0.4 on 2020-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200514_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Gaming', 'Gaming'), ('Computing', 'Computing'), ('Politics', 'Politics'), ('Philosophy', 'Philosophy'), ('CoderDojo', 'CoderDojo'), ('Culture', 'Culture')], default='Tech', max_length=20),
        ),
    ]
