# Generated by Django 3.0.4 on 2020-05-21 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200515_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Gaming', 'Gaming'), ('Computing', 'Computing'), ('Politics', 'Politics'), ('Philosophy', 'Philosophy'), ('CoderDojo', 'CoderDojo'), ('Culture', 'Culture'), ('Tutorials', 'Tutorials'), ('Science', 'Science')], default='Tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='middleImage',
            field=models.CharField(default='No image', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='references',
            field=models.TextField(default='No references', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(default='No subtitle', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='topImage',
            field=models.CharField(default='No image', max_length=100),
        ),
    ]
