# Generated by Django 3.0.4 on 2020-06-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200521_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='None', max_length=100),
        ),
    ]
