# Generated by Django 3.0.4 on 2020-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Tutorials', 'Tutorials'), ('Projects', 'Projects')], default='Tech', max_length=20),
        ),
    ]
