# Generated by Django 3.0.4 on 2021-01-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200718_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='extraImage1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='extraImage1Description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='extraImage2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='extraImage2Description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='extraImage3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='extraImage3Description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='middleImage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='middleImageDescription',
        ),
        migrations.RemoveField(
            model_name='post',
            name='references',
        ),
        migrations.RemoveField(
            model_name='post',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topImage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topImageDescription',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Tutorials', 'Tutorials'), ('Projects', 'Projects'), ('Computing', 'Computing'), ('Culture', 'Culture'), ('Thoughts', 'Thoughts')], default='Tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='text1',
            field=models.TextField(default='No text', max_length=7000),
        ),
        migrations.AlterField(
            model_name='post',
            name='text2',
            field=models.TextField(default='No text', max_length=7000),
        ),
    ]
