# Generated by Django 3.0.4 on 2021-01-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20210106_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topImage',
            field=models.CharField(default='No image', max_length=100),
        ),
    ]
