# Generated by Django 3.0.4 on 2021-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_post_topimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Tutorials', 'Tutorials'), ('Projects', 'Projects'), ('Computing', 'Computing'), ('Culture', 'Culture')], default='Tech', max_length=20),
        ),
    ]
