# Generated by Django 3.0.4 on 2021-05-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
