# Generated by Django 3.0.4 on 2021-05-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0002_auto_20210511_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
